name: CTSMPCore
version: '1.0-SNAPSHOT'
main: me.lunafy.ctsmpcore.CTSMPCore
api-version: 1.18
authors: [ Lunafy ]
description: The Core Framework to CTSMP
commands:
  newheart:
    usage: /<command>
  sethearts:
    usage: /<command>
  friend:
    usage: /<command>